"""Add table 'secret'

Revision ID: 95c1ff31b692
Revises: 
Create Date: 2020-09-04 16:26:21.392586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c1ff31b692'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('secret_phrase', sa.Text(), nullable=True),
    sa.Column('code_phrase', sa.String(length=200), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_code_phrase'), 'secret', ['code_phrase'], unique=False)
    op.create_index(op.f('ix_secret_id'), 'secret', ['id'], unique=False)
    op.create_index(op.f('ix_secret_secret_key'), 'secret', ['secret_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secret_secret_key'), table_name='secret')
    op.drop_index(op.f('ix_secret_id'), table_name='secret')
    op.drop_index(op.f('ix_secret_code_phrase'), table_name='secret')
    op.drop_table('secret')
    # ### end Alembic commands ###
